### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by alex-nexus** [bcfalah/music-service-api#3]
How would you approach performance tuning? Any specific endpoint you think would good candidates for performance tuning?

**Comment by bcfalah** [comment]
Well, I have already added all the database indexes I think it could be of help, and we could add more if necessary (by previously doing an explain query), but I don't think this would be necessary by now, as we don't have filters in the indexes or special queries to do.

We could also make sure that we don't have any "N+1" problem when rendering the views (I think we probably have this problem right now), if we find them, we can easily add an _include_ in the controllers and that's all we need.

Apart of those things, I would proabably implement caching, this could make a big difference in terms of reponse times.

I think that we should specially check and add this implementations to our  _index_ and _show_ endpoints, which are the ones that generally perform the same _SELECT_ queries and retrieve many resources (and sometimes this resources retrieve another ones).

**Comment by alex-nexus** [comment]
great, thanks.
